export default {
  left: 'x 坐标',
  top: 'y 坐标',
  height: '高',
  width: '宽',
  color: '颜色',
  backgroundColor: '背景色',
  borderWidth: '边框宽度',
  borderColor: '边框颜色',
  borderRadius: '边框半径',
  fontSize: '字体大小',
  fontWeight: '字体粗细',
  lineHeight: '行高',
  letterSpacing: '字间距',
  textAlign: '对齐方式',
  opacity: '透明度',
}
